apiVersion: v1
kind: Service
metadata:
  name: dabacluster
  labels:
    name: dabacluster
spec:
  type: NodePort
  ports: 
  - port: 80      
    nodePort: 32000                           # 指明暴露在外端口的port  
  selector:
    name: dabacluster
